code --install-extension 13xforever.language-x86-64-assembly
code --install-extension alefragnani.Bookmarks
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension Dart-Code.dart-code
code --install-extension eamodio.gitlens
code --install-extension gbasood.byond-dm-language-support  
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension icrawl.discord-vscode
code --install-extension infosec-intern.yara
code --install-extension ipid.asm-comment-aligner
code --install-extension James-Yu.latex-workshop
code --install-extension jbockle.jbockle-format-files       
code --install-extension mathiasfrohlich.Kotlin
code --install-extension maziac.asm-code-lens
code --install-extension ms-azuretools.vscode-docker        
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh        
code --install-extension ms-vscode-remote.remote-ssh-edit   
code --install-extension ms-vscode-remote.remote-wsl        
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension RReverser.llvm
code --install-extension ryu1kn.partial-diff
code --install-extension samuelcolvin.jinjahtml
code --install-extension softwaredotcom.swdc-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension vscodevim.vim
code --install-extension william-voyek.vscode-nginx
code --install-extension ZixuanWang.linkerscript
