multitenancy_enabled: false
target: all,alertmanager,overrides-exporter

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: mimir
      secret_access_key: supersecret
      insecure: true
      bucket_name: mimir

blocks_storage:
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /data/tsdb

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager

ruler_storage:
  s3:
    bucket_name: mimir-ruler

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback-config.yaml
  external_url: http://mimir:9009/alertmanager

alertmanager_storage:
  s3:
    bucket_name: mimir-alertmanager

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

server:
  http_listen_port: 9009
  grpc_listen_port: null
  # grpc_listen_port: 0
  # grpc_listen_conn_limit: 0
  log_level: warn
