multitenancy_enabled: false
target: all,alertmanager

blocks_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-blocks
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true
  tsdb:
    dir: /data/ingester

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager

ruler_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-ruler
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback-config.yaml
  external_url: http://mimir:9009/alertmanager

alertmanager_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-alertmanager
    access_key_id: mimir
    secret_access_key: supersecret
    insecure: true

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

server:
  http_listen_port: 9009
  log_level: warn
