server:
  log_level: warn

metrics:
  global:
    scrape_interval: 5s
    scrape_timeout: 3s # default
    remote_write:
      - url: http://localhost:49009/api/v1/push
  configs:
    - name: default
      scrape_configs:
        # - job_name: cadvisor
        #   metric_relabel_configs:
        #     - regex: "(container_label_com_docker_compose_config_hash|container_label_com_docker_compose_container_number|container_label_com_docker_compose_oneoff|container_label_com_docker_compose_version|container_label_maintainer|container_label_org_label_schema_schema_version|container_label_org_label_schema_vcs_ref)"
        #       action: labeldrop
        #   static_configs:
        #     - targets: ["localhost:48080"]

logs:
  configs:
    - name: default
      clients:
        - url: http://localhost:43100/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: varlogs
          static_configs:
            - targets: [localhost]
              labels:
                job: varlogs
                __path__: /var/log/*log
        - job_name: journal
          journal:
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels: ["__journal__systemd_unit"]
              target_label: "systemd_unit"
            - source_labels: ["__journal__hostname"]
              target_label: "nodename"
            - source_labels: ["__journal_syslog_identifier"]
              target_label: "syslog_identifier"

integrations:
  agent:
  cadvisor_config:
  node_exporter:
