---
- name: Check OMZ installed
  stat:
    path: /usr/share/oh-my-zsh/
  register: check_omz_result

- name: Ending playbook if OMZ installed
  meta: end_host
  when: check_omz_result.stat.exists and not force_omz

- name: Install zsh, git, curl, wget
  apt:
    pkg:
      - zsh
      - git
      - wget
      - curl
    state: latest
    update_cache: true
  become: true

- name: Get OMZ installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_omz.sh

- name: Get patch
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/plain/0001-zshrc.patch?h=oh-my-zsh-git
    dest: /tmp/zshrc.patch

- name: Install OMZ
  ansible.builtin.command: /bin/sh /tmp/install_omz.sh --unattended
  become: true

- name: mv root OMZ
  command: mv /root/.oh-my-zsh/ /usr/share/oh-my-zsh/
  become: true

- name: Copy zshrc
  copy:
    src: /usr/share/oh-my-zsh/templates/zshrc.zsh-template
    dest: /usr/share/oh-my-zsh/zshrc
    remote_src: yes
  become: true

- name: Patch
  ansible.posix.patch:
    basedir: /usr/share/oh-my-zsh/
    src: /tmp/zshrc.patch
    remote_src: yes
    strip: 1
  become: true

- name: Link sketelon
  file:
    src: "/usr/share/oh-my-zsh/zshrc"
    dest: "/etc/skel/.zshrc"
    state: link
  become: true

- name: Copy zshrc
  copy:
    src: /usr/share/oh-my-zsh/zshrc
    dest: /root/.zshrc
    remote_src: true
  become: true

- name: Clear tmp
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/install_omz.sh
    - /tmp/zshrc.patch
